steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args: [
         'gcloud',
         'beta',
         'functions',
         'deploy',
         'trellis-job-launcher',
         '--project=${PROJECT_ID}',
         '--source=functions/job-launcher',
         '--memory=256MB',
         '--max-instances=100',
         '--timeout=120',
         '--entry-point=launch_job',
         '--runtime=python37',
         '--trigger-topic=${_TRIGGER_TOPIC}',
         '--update-env-vars=CREDENTIALS_BUCKET=${_CREDENTIALS_BUCKET}',
         '--update-env-vars=CREDENTIALS_BLOB=${_CREDENTIALS_BLOB}',
         '--update-env-vars=ENVIRONMENT=${_ENVIRONMENT}',
         '--update-env-vars=ENABLE_JOB_LAUNCH=${_ENABLE_JOB_LAUNCH}',
         # Fix for logging issue: https://issuetracker.google.com/issues/155215191#comment112
         '--update-env-vars=USE_WORKER_V2=true',
         '--update-env-vars=PYTHON37_DRAIN_LOGS_ON_CRASH_WAIT_SEC=5',
         '--update-labels=user=trellis',
  ]
