steps:
- name: 'ubuntu'
  args: ['ls', 'config/${_DATA_GROUP}']
- name: 'ubuntu'
  args: ['cp',
         'config/${_DATA_GROUP}/database-triggers.py',
         'functions/check-triggers/']
- name: 'ubuntu'
  args: ['ls', 'functions/check-triggers']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args: [
         'gcloud', 'functions', 'deploy', 'trellis-check-triggers',
         '--project=${PROJECT_ID}',
         '--source=functions/check-triggers',
         '--memory=256MB',
         '--max-instances=20',
         '--entry-point=check_triggers',
         '--runtime=python37',
         '--trigger-topic=${_TRIGGER_TOPIC}',
         '--update-env-vars=CREDENTIALS_BUCKET=${_CREDENTIALS_BUCKET}',
         '--update-env-vars=CREDENTIALS_BLOB=${_CREDENTIALS_BLOB}',
         '--update-env-vars=ENVIRONMENT=${_ENVIRONMENT}',
         # Fix for logging issue: https://issuetracker.google.com/issues/155215191#comment112
         '--update-env-vars=USE_WORKER_V2=true',
         '--update-env-vars=PYTHON37_DRAIN_LOGS_ON_CRASH_WAIT_SEC=5',
         '--update-labels=user=trellis',
  ]
