# DEPRECATED: Jobs now configured by individual YAMLs in the job-launcher/jobs directory
--- !TaskConfiguration
name: fastq-to-ubam
dsub_prefix: fq2u
job_request_id: ${jobRequestUuid}
parameters:
  - sample
  - readGroup
  - jobRequestUuid
virtual_machine:
  min_cores: 1
  min_ram: 7.5
  boot_disk_size: 20
  disk_size: 500
  image: broadinstitute/gatk:4.1.0.0
dsub:
  preemptible: False
  inputs:
      FASTQ_R1: "{sample}/HAS_READ_GROUP/{readGroup}/HAS_PAIRED_END_FASTQ/*R1.fastq.gz$"
      FASTQ_R2: "{sample}/HAS_READ_GROUP/{readGroup}/HAS_PAIRED_END_FASTQ/*R2.fastq.gz$"
  env_variables:
      RG: "{readGroup}"
      SM: "{sample}"
      PL: "illumina"
  outputs:
      UBAM: "/{sample}/HAS_READ_GROUP/{readGroup}/HAS_PAIRED_END_FASTQ/{jobRequestUuid}_{sample}_{readGroup}.ubam"
  command: "/gatk/gatk --java-options
    \\'-Xmx8G -Djava.io.tmpdir=bla\\'
    FastqToSam
    -F1 ${FASTQ_R1}
    -F2 ${FASTQ_R2}
    -O ${UBAM}
    -RG ${RG}
    -SM ${SM}
    -PL ${PL}"
  labels:
    read-group: "{readGroup}"
    sample: "{sample}"
  