# create-blob-node variables
LABEL_TAXONOMY: label-taxonomy.json
DATA_GROUP: phase3
TOPIC_DB_QUERY: trellis-db-query

# db-query variables
USER_DEFINED_QUERIES: user-defined-queries.yaml
CREATE_BLOB_QUERIES: create-blob-queries.yaml 
CREATE_JOB_QUERIES: create-job-queries.yaml

NEO4J_SCHEME: bolt
NEO4J_IP_ADDRESS:
NEO4J_PORT: 7687
NEO4J_PASSPHRASE:

TOPIC_TRIGGERS: trellis-check-triggers
TOPIC_JOB_LAUNCHER: trellis-job-launcher

# job-launcher variables
DSUB_OUTPUT_BUCKET: 
DSUB_LOG_BUCKET: 
DSUB_USER: trellis
DSUB_REGIONS: us-west2