steps:
- name: 'ubuntu'
  args: ['cp',
         'config/job-launcher.yaml',
         'functions/job-launcher/']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args: [
         'gcloud',
         'beta',
         'functions',
         'deploy',
         'trellis-job-launcher',
         '--project=${PROJECT_ID}',
         '--source=functions/job-launcher',
         '--memory=256MB',
         '--max-instances=100',
         '--timeout=120',
         '--entry-point=launch_job',
         '--runtime=python312',
         '--region=us-west2',
         '--gen2',
         '--trigger-topic=${_TRIGGER_TOPIC}',
         '--update-env-vars=CREDENTIALS_BUCKET=${_CREDENTIALS_BUCKET}',
         '--update-env-vars=CREDENTIALS_BLOB=${_CREDENTIALS_BLOB}',
         '--update-env-vars=ENVIRONMENT=${_ENVIRONMENT}',
         '--update-env-vars=ENABLE_JOB_LAUNCH=${_ENABLE_JOB_LAUNCH}',
         '--update-labels=user=trellis',
  ]
